#!/bin/bash

csso='node_modules/csso/bin/csso'
cssDir='server/public/css'

find src/js server -type f -name '*.coffee' -exec coffee -c '{}' +
find server -type f -name '*.scss' -exec sass --update -t compressed -f '{}' +

echo \
    $(${csso} "${cssDir}/base.css")     \
    $(${csso} "${cssDir}/skeleton.css") \
    $(${csso} "${cssDir}/layout.css")   \
    $(${csso} "${cssDir}/pipeline.css") > "${cssDir}/compiled.css"
