#!/bin/bash -x

clientLib='src/js/lib'
serverJS='server/public/js'

ln -fs ../../../sub/zepto/dist/zepto.js ${clientLib}
ln -fs ../../../sub/underscore/underscore.js ${clientLib}
ln -fs ../../../sub/backbone/backbone.js ${clientLib}
ln -fs ../../../sub/text/text.js ${clientLib}
ln -fs lib/text.js src/js/text.js

ln -fs ../../../build/js/pipeline.js ${serverJS}
ln -fs ../../../node_modules/grunt-requirejs/node_modules/requirejs/require.js ${serverJS}
ln -nfs ../../../src/js "${serverJS}/src"
