// Generated by CoffeeScript 1.3.3
(function() {
  var index, loader, urls;

  loader = new Loader;

  urls = [];

  index = 5;

  loader.loadNext(function(loaded) {
    urls = loaded;
    $('#goldie').append("<img src='" + urls[index] + "' />");
    return console.log(urls);
  });

  $(window).keydown(function(event) {
    var _ref;
    if ((_ref = event.which) === 37 || _ref === 39) {
      switch (event.which) {
        case 37:
          index -= 1;
          break;
        case 39:
          index += 1;
      }
      if (urls[index]) {
        return $('#goldie').html("<img src='" + urls[index] + "' />");
      }
    }
  });

}).call(this);
