// Generated by CoffeeScript 1.3.3
(function() {
  var loader;

  loader = new Loader;

  loader.setup(function(url) {
    $('#goldie').append("<img src='" + url + "' />");
    return $(window).keydown(function(event) {
      var _ref;
      if ((_ref = event.which) === 37 || _ref === 39) {
        url = (function() {
          switch (event.which) {
            case 37:
              return loader.prevUrl();
            case 39:
              return loader.nextUrl();
          }
        })();
        console.log("url is " + url);
        return $('#goldie').html("<img src='" + url + "' />");
      }
    });
  });

}).call(this);
