// Generated by CoffeeScript 1.3.3
(function() {

  window.Loader = (function() {

    function Loader() {
      this._count = 0;
      this._before = null;
      this._after = null;
    }

    Loader.prototype.loadNext = function(callback) {
      var params;
      this._count += 25;
      params = "count=" + this._count;
      if (this._before) {
        params += "&after=" + this._after;
      }
      return this.loadUrls(params, callback);
    };

    Loader.prototype.loadPrev = function(callback) {
      var params;
      this._count -= 25;
      params = "count=" + this._count;
      if (this._before) {
        params += "&before=" + this._before;
      }
      return this.loadUrls(params, callback);
    };

    Loader.prototype.loadUrls = function(params, callback) {
      var _this = this;
      return $.ajax({
        type: 'GET',
        url: "http://www.reddit.com/r/realasians.json?" + params,
        dataType: 'jsonp',
        jsonp: 'jsonp',
        success: function(data) {
          var link, url, urls, valid;
          _this._before = data.data.before;
          _this._after = data.data.after;
          urls = (function() {
            var _i, _len, _ref, _results;
            _ref = data.data.children;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              link = _ref[_i];
              _results.push(link.data.url);
            }
            return _results;
          })();
          valid = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = urls.length; _i < _len; _i++) {
              url = urls[_i];
              if (Utils.isImageUrl(url)) {
                _results.push(url);
              }
            }
            return _results;
          })();
          return callback(valid);
        }
      });
    };

    return Loader;

  })();

}).call(this);
