// Generated by CoffeeScript 1.3.3
(function() {

  window.Utils = (function() {

    function Utils() {}

    Utils.isImageUrl = (function() {
      var types;
      types = ['jpg', 'png'];
      return function(url) {
        var type, _i, _len;
        for (_i = 0, _len = types.length; _i < _len; _i++) {
          type = types[_i];
          if (Utils.endsWith(url, type)) {
            return true;
          }
        }
        return false;
      };
    })();

    Utils.endsWith = function(str, end) {
      return str.slice(str.length - end.length) === end;
    };

    return Utils;

  })();

}).call(this);
